### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kita2345** [tuyafeng/Via#1030]
Phone: asus ASUS_X01BDA(WW_X01BD)
App Version: 4.3.5(20220125)
Snapshot Time: 2022-02-01 18:17:10
CPU ABI: arm64-v8a 
Screen: 2079x1080
Android Version: 9 API28
Language: in-ID
WebView Impl: com.android.chrome
WebView Version: 97.0.4692.98(469209823)
```
[2022-01-30 20:26:17.638] E/(Thread[RxCachedThreadScheduler-1,5,main]): javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0x77ba62aa08: I/O error during system call, Connection reset by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
	at mark.via.m.m.j0.f(Unknown Source:18)
	at mark.via.m.m.j0.b(Unknown Source:64)
	at mark.via.l.x3.v6(Unknown Source:0)
	at mark.via.l.e1.run(Unknown Source:6)
	at e.a.a.b.o$a.run(Unknown Source:9)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
[2022-01-31 16:37:11.409] E/(Thread[RxCachedThreadScheduler-66,5,main]): java.io.IOException: unexpected end of stream on com.android.okhttp.Address@9cb6c641
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
	at mark.via.m.m.j0.f(Unknown Source:18)
	at mark.via.m.m.j0.b(Unknown Source:64)
	at mark.via.l.x3.v6(Unknown Source:0)
	at mark.via.l.e1.run(Unknown Source:6)
	at e.a.a.b.o$a.run(Unknown Source:9)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	... 20 more
[2022-02-01 17:57:58.269] E/(Thread[main,5,main]): java.util.zip.ZipException: duplicate entry: info.txt
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:234)
	at mark.via.m.m.l0.b(Unknown Source:33)
	at mark.via.m.m.l0.a(Unknown Source:43)
	at mark.via.y.k2.N2(Unknown Source:17)
	at mark.via.y.r.call(Unknown Source:8)
	at io.reactivex.rxjava3.internal.operators.observable.g.A(Unknown Source:17)
	at e.a.a.b.k.b(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn.A(Unknown Source:27)
	at e.a.a.b.k.b(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$a.run(Unknown Source:6)
	at e.a.a.a.b.c$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at com.tuyafeng.support.crash.a$a.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[2022-02-01 17:58:09.559] E/(Thread[main,5,main]): java.util.zip.ZipException: duplicate entry: info.txt
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:234)
	at mark.via.m.m.l0.b(Unknown Source:33)
	at mark.via.m.m.l0.a(Unknown Source:43)
	at mark.via.y.k2.N2(Unknown Source:17)
	at mark.via.y.r.call(Unknown Source:8)
	at io.reactivex.rxjava3.internal.operators.observable.g.A(Unknown Source:17)
	at e.a.a.b.k.b(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn.A(Unknown Source:27)
	at e.a.a.b.k.b(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$a.run(Unknown Source:6)
	at e.a.a.a.b.c$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at com.tuyafeng.support.crash.a$a.run(Unknown Source:0)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by tuyafeng** [comment]
收到，感谢你的反馈，该问题已解决。
