### ISSUE TITLE
java.lang.IllegalStateException: Fragment c0{2f68eea} (0e3b13fc-2efb-4ba2-9b46-91cbb0a7b1c6) not attached to a context.

### ISSUE THREAD

**Issue by Kita2345** [tuyafeng/Via#1076]
```
Phone: asus ASUS_X01BDA(WW_X01BD)
App Version: 4.3.7(20220331)
Snapshot Time: 2022-04-11 19:38:18
CPU ABI: arm64-v8a 
Screen: 2089x1080
Android Version: 9 API28
Language: in-ID
WebView Impl: com.android.chrome
WebView Version: 100.0.4896.79(489607923)

[2022-04-11 19:38:13.243] E/(Thread[main,5,main]): java.lang.IllegalStateException: Fragment c0{2f68eea} (0e3b13fc-2efb-4ba2-9b46-91cbb0a7b1c6) not attached to a context.
	at androidx.fragment.app.Fragment.a(Unknown Source:31)
	at mark.via.q.c0.e3(Unknown Source:12)
	at mark.via.q.c0.f3(Unknown Source:0)
	at mark.via.q.m.call(Unknown Source:2)
	at io.reactivex.rxjava3.internal.operators.single.b.i(Unknown Source:16)
	at e.a.a.b.p.b(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source:2)
	at e.a.a.b.o$a.run(Unknown Source:9)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by AyakaAgo** [comment]
```+1``` I got this error too

Probably since ```swipe-back``` gesture was added to Settings, About and Dialogs.

This is rarely occurs *(happened 3 times on my device)* with a toast displayed and does'nt affect use. @tuyafeng
