### ISSUE TITLE
when scrolling a web page, the browser often crashes

### ISSUE THREAD

**Issue by NektoNektovich** [tuyafeng/Via#1291]
Android 6.0  armv7a
Mediatek 6737m
very good browser 👍 but there is a problem - when scrolling a web page, the browser often crashes, and often reboots the phone and this happens on any version of the via browser, now on 4.5.1😩 with firefox and fulguris there is no such problem 🤔 please fix it!

**Comment by NektoNektovich** [comment]
>

**Comment by tuyafeng** [comment]
Can you post the debugging log here (Settings - About - Click the logo)?

**Comment by Apaaja20** [comment]
```
Phone: Sony E6653(E6653)
Package: mark.via.gp
App Version: 4.5.1(20230222)
Snapshot Time: 2023-03-01 16:21:58
CPU ABI: arm64-v8a 
Screen: 1812x1080
Android Version: 7.1.1 API25
Language: id-ID
WebView Impl: com.chrome.dev
WebView Version: 112.0.5610.0(561000023)

[2023-02-22 20:30:18.729] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/BB4B-1E1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:427)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[2023-02-23 05:13:31.755] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/BB4B-1E1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:427)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[2023-02-23 06:39:56.333] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/BB4B-1E1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:427)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[2023-02-23 06:41:17.418] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/BB4B-1E1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:427)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[2023-02-23 06:43:23.608] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/BB4B-1E1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:427)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[2023-02-23 06:43:52.418] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/BB4B-1E1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:427)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[2023-02-23 17:18:52.994] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/BB4B-1E1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:427)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:6274)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
[2023-02-23 17:19:42.076] E/(Thread[RxCachedThreadScheduler-29,5,main]): java.lang.UnsupportedOperationException: Delete not supported
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.delete(ContentProviderNative.java:550)
	at android.content.ContentResolver.delete(ContentResolver.java:1376)
	at i.a.r.t.g0.d()
	at i.a.v.a1.i3()
	at i.a.v.a1.W3()
	at i.a.v.a1.X3()
	at i.a.v.o.call()
	at f.a.a.f.e.d.a.i()
	at f.a.a.b.p.b()
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run()
	at f.a.a.b.o$a.run()
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run()
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call()
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by NektoNektovich** [comment]
> Can you post the debugging log here (Settings - About - Click the logo)?

Phone: Texet TM-4510(TM-4510)
Package: mark.via.gp
App Version: 4.5.1(20230222)
Snapshot Time: 2023-03-01 14:57:35
CPU ABI: armeabi-v7a armeabi
Screen: 854x480
Android Version: 6.0 API23
Language: ru
WebView Impl: com.google.android.webview
WebView Version: 106.0.5249.163(1666487110)

[2023-02-26 12:08:28.201] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[2023-02-26 12:38:06.8] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[2023-02-26 13:03:42.843] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[2023-02-26 14:00:06.136] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[2023-03-01 14:11:00.491] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
@

**Comment by NektoNektovich** [comment]
> Can you post the debugging log here (Settings - About - Click the logo)?

Phone: Texet TM-4510(TM-4510)
Package: mark.via.gp
App Version: 4.5.1(20230222)
Snapshot Time: 2023-03-01 14:57:35
CPU ABI: armeabi-v7a armeabi
Screen: 854x480
Android Version: 6.0 API23
Language: ru
WebView Impl: com.google.android.webview
WebView Version: 106.0.5249.163(1666487110)

[2023-02-26 12:08:28.201] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[2023-02-26 12:38:06.8] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[2023-02-26 13:03:42.843] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[2023-02-26 14:00:06.136] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
[2023-03-01 14:11:00.491] W/(Thread[main,5,main]): java.lang.UnsupportedOperationException: Unsupported Uri content://com.android.externalstorage.documents/tree/FA64-1F1E%3A
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:498)
	at android.content.ContentResolver.query(ContentResolver.java:441)
	at i.a.r.t.g0.i()
	at i.a.t.h.j.p1()
	at i.a.e0.o3.Q1()
	at androidx.fragment.app.Fragment.p2()
	at b.h.d.t.f()
	at b.h.d.t.m()
	at androidx.fragment.app.FragmentManager.a0()
	at androidx.fragment.app.FragmentManager.c1()
	at androidx.fragment.app.FragmentManager.X()
	at androidx.fragment.app.FragmentManager$d.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at d.f.g.l.a$a.run()
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5737)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
